const actionTypes = {
  //Village actions
  SET_USER: "SET_USER",
  SET_VILLAGE: "SET_VILLAGE",
  SET_VILLAGES: "SET_VILLAGES",
  GET_VILLAGE: "GET_VILLAGE",
  GET_VILLAGES: "GET_VILLAGES",
  GET_OTHER_VILLAGES: "GET_OTHER_VILLAGES",

  //Attack actions
  SEND_ATTACK: "SEND_ATTACK",
  GET_ATTACKS: "SEND_ATTACK",
  SET_ATTACKS: "SEND_ATTACK",

  //Middleware return types
  PENDING: "_PENDING",
  FULFILLED: "_FULFILLED",
  REJECTED: "_REJECTED",
}

export default actionTypes
